// breakpoints
export const screenXxxsMax = "375px"
export const screenXxsMax = "479px"
export const screenXsMin = "480px"
export const screenXsMax = "767px"
export const screenSmMin = "768px"
export const screenSmMax = "991px"
export const screenMdMin = "992px"
export const screenMdMax = "1199px"
export const screenLgMin = "1200px"
export const screenLgMax = "1919px"
export const screenXlMin = "1920px"
