// import { Epigraph } from "@/utils/layout"
import { ArticleStyles, } from "./styled"

// import { Base } from "@/components"

import { SignatureContainer, } from "../../styled"

import "../../styles.css"

import CamilleTitleCard from "../../../../../../public/photos/Jupiter_Issue4_title-cards-camille_02_03.jpg"
import SaltShed from "../../../../../../public/photos/salt-shed.jpg"

export function Article() {
  return (
    <ArticleStyles>
    <br/>
    <div>
        <div style={{ display: "flex", flexDirection: "column", padding: "0 1%", }}>
      <SignatureContainer src={CamilleTitleCard} alt="Camille Title Card" className="titlecard" />
        </div>
    <br/>

    <p className="Camille-Bacon-04">
    <i> &#8220;It says that, as a talking bird, the raven… <br/>
    represents prophecy and insight.&#8221; </i> <a href="https://www.vulture.com/2023/02/kelela-raven.html" target="_blank" className="styled"> —Kelela </a>
    <br/><br/>
    <span className="justified"> She opens with her song. &#8220;She&#8221; as in Kelela, &#8220;her&#8221; as in a woman I was seeing. </span>
    <br/>
    That night, September prepared to take her curtain call and a crescent moon dangled delicately above Chicago&#39;s Salt Shed as Kelela crooned the final lines of &#8220;<a href="https://www.youtube.com/watch?v=FQ-zGi6zyPw" target="_blank" className="styled"> Cherry Coffee </a>&#8221; and slipped, without warning, into &#8220;<a href="https://www.youtube.com/watch?v=XQEGP3CaWEs" target="_blank" className="styled">Jupiter. </a>&#8221; We&#39;d talked about these songs before, the ones we regard as respective sonic portraits of ourselves, the ones that unburden our breath. 
    <br/><br/>
    <div style={{ display: "flex", flexDirection: "column", padding: "0 1%", }}>
      <SignatureContainer src={SaltShed} alt="Kelela performing at the Salt Shed by Joel Meinholz" className="textinnerimg hor camille" />
    </div>
    <br/>
    <span className="centered small"> Kelela performing at the Salt Shed by Joel Meinholz </span>
    <br/>  
    Several months earlier the moon yawned itself toward totality, giving all of us gathered at Good Room, Brooklyn <sup><a href="#fn1" id="ref1">1</a></sup> a beacon to howl at. I gathered there with two friends to attend Kelela&#39;s rave, where her recently released <a href="https://www.youtube.com/watch?v=5l3sE4Y5-vw&list=PLjpdY-hPtpeNy8wqkOwZXo4jMsz6u2yFR" target="_blank" className="styled"> RAVE:N, The Remixes </a>  was reinterpreted by DJs including BEARCAT, DJ SWISHA, and Niara Sterling &#40;among others&#41;, coalescing into a centripetal force of thrashing sound to spin, amplify, and release our storms of sentiment into. 
    <br/><br/>
    Awash in a pandemonious symphony of synth and strobe, a new prism through which to see in the dark emerged from the throbbing crowd like another beacon. Her right cheek was punctuated with a beauty mark whose form is akin to an inverted exclamation point, or a trembling star. Even as she flickered in and out of view, fusing with the oceanic magma of the crowd, the fact of her existence was the centrifuge around which my attention singularly focused. Her gaze, decidedly directed at the DJ booth, rhymed with the moon spilling itself open above us, her eyes, ablaze, not waning / but waxing, and drawing all the water in my body toward her. Like Kelela&#39;s catalog, how she struck me was fierce and immediate—blaring and harmonizing with the dense and decadent belly of the club into which she disappeared shortly after.


    <br/><br/>
    Kelela&#39;s albums, EP, and mixtapes are a blazing totem around which so many of us gather to feel the gravity, consequence, and sanctity of our own selves. If it is indeed true—and I think it is—that, as Audre Lorde <a href="https://makinglearning.wordpress.com/wp-content/uploads/2014/01/poetry-is-not-a-luxury-audre-lorde.pdf" target="_blank" className="styled"> writes </a>, &#8220;the quality of light by which we scrutinize our lives has direct bearing upon the product which we live, and upon the changes which we hope to bring about through those lives,&#8221; then Kelela&#39;s discography is one that has, since 2017, vastly sharpened and made more exacting the glimmering beams through which I shape and reshape &#8220;the product which [I] live.&#8221; Her sonic worlds extend permission to demand more for myself from my relationships, namely my romantic commitments. 
    <br/><br/>
    <a href="https://www.youtube.com/watch?v=l227G1KSWks&list=OLAK5uy_n0YCnLhLgsZdJLXjvL7ZZUkKR_MUu7YrU" target="_blank" className="styled"> <i> Take Me Apart &#40;2017&#41;,</i></a> a bildungsroman of an album, pervaded my second coming of age: the period in which I was excising and clawing my way out of malignant intimacies and beginning to understand which faces of the divine were mine to mirror. <a href="https://kelela.warp.net/format/229637-hallucinogen" target="_blank" className="styled"> <i> Hallucinogen &#40;2015&#41;</i></a> and <a href="https://www.youtube.com/watch?v=9oX4v5WyM5A&list=OLAK5uy_l7t3MyMHb1xAtvJg6KZw675meEPMNNysg" target="_blank" className="styled"> <i>CUT 4 ME &#40;2013&#41;,</i></a> her first two releases &#40;a mixtape and EP respectively&#41;, are the places I go when I need to remember how sacred my unruliness is. <a href="https://kelela.warp.net/format/1177020-raven" target="_blank" className="styled"> <i>Raven &#40;2023&#41;,</i></a> her second studio production wherein, as Kelela shared in an <a href="https://www.vulture.com/2023/02/kelela-raven.html" target="_blank" className="styled"> interview, </a> &#8220;a lot of what [she&#39;s] dealing with is the emotional stuntedness of men,&#8221; washed me back up onto my own shores in the aftermath of relationships which, even in their magnificence, flattened me. The chorus of her offerings are trusted companions as I continue to learn how to love responsibly, as I stand on the ledge of becoming. 
    <br/><br/>
    On that brimming September evening in Chicago, Kelela emerged from under an oneiric canopy of orange light and took her mark on a stage populated only by her body and a grand piano. Draped in a dress hued somewhere between freshly drawn blood and a voluptuous red wine, she stood as if on a baptismal font. 
    <br/><br/>
    Our siren offered us a sonorous serenade, the flesh of each song stripped back to expose its ivory skeleton. Her voice, laced with the piano&#39;s adagios, conjured a cathedral of feeling in the air above our heads, one expansive enough for the full environment of our emotions to dwell in. The music&#39;s potent bareness, its reduction to the most essential sum of parts, was mirrored by the mode of illumination that flooded the sparse stage. Right before her performance began, an architectural matrix of metallic bars &#40;a structure that&#39;s usually left suspended up high where it remains largely invisible to the audience&#41; with a row of spotlights clinging to its length crawled languidly toward the ground. Kelela&#39;s acoustic ballads filled the air like intoxicants, coaxing a swell of embodied aqueous flow. Friends and lovers held close to one another and swayed beneath her, <br/>
    as if a congregation.  
    <br/><br/>
    Yes, those of us who return to Kelela&#39;s gospel as many do a pew are indeed our own congregation and it is to church &#40;thought of most expansively here&#41; we go to seek guidance in the face of the muddied clarity and gnarled magnificence that accompanies any rupture.
    <br/><br/>
    Some days after Good Room and some weeks before Salt Shed, &#8220;<a href="https://www.youtube.com/watch?v=sGX9GawLLZY&list=OLAK5uy_mm8aLnmMzldAQiM2RuNz0mtm4ZsiwhEBY&index=11" target="_blank" className="styled"> Bruises</a>&#8221; blared through my brain and, amidst my own heartbreak, I decided to try and <i> &#8220;find another way.&#8221; </i> I thought that meant turning the headlights of my heart in a different direction entirely toward new lovers. Under the mercy of the music I&#39;ve since arrived at a second reading of the lyric, one that gives credence to the possibility of repair, in finding &#8220;another way&#8221; toward a road already trodden. Or, perhaps that path is actually the <i> &#8220;right, right, right, right, just right&#8221; </i> of the reminder that my <i> own </i> love for my <i> own </i> self is the endless clearing, the fountain of infinitude, the cosmic loop always making more of itself.
    <br/><br/>
    This insight comes to a head in the reflecting pool that is Kelela&#39;s &#8220;<a href="https://www.youtube.com/watch?v=XQEGP3CaWEs" target="_blank" className="styled">Jupiter.</a>&#8221; The piercingly sincere lullaby indexes two stages of resurgence and calls to mind what Octavia Butler&#39;s protagonist Lauren Oya Olamina said in <i> Parable of the Sower </i> &#40;1993&#41; about how &#8220;In order to rise / From its own ashes / A phoenix / First / Must / Burn&#8221;—a naming of what it takes to resurrect from your own debris by inhabiting the dense forest of mourning that all endings espouse and willing yourself to hold faith in the fact that your heart will come around the bend, that you will land in a glade more verdant and resplendent than you ever could have imagined, that a love that meets your shore with ease is an inevitability if you choose to believe it so &#40;<i>&#8220;find a light in a cold color&#8221;</i>&#41; and, by waking up everyday willing to inhabit the aching kiln of self-revelation, to look at the entire expanse of yourself unflinchingly: the rugged edges, all the parts the river has yet to run smooth, all the metal that refuses to be mollified &#40;<i>&#8220;I think I know me now&#8221;</i>&#41;.
    <br/><br/>
    Both of these phases require you to be brave enough to make an ally of the metaphysical mystery, to accept the ambivalence of an unsteady heart, to refuse to force your own hand, to inhabit the moments that precede a shedding of skin as their own quiet triumph. They demand a stratospheric degree of emotional, spiritual, mental, and somatic rigor, all forged and intensified in a crucible of adoration from all those that hold up a magnifying glass to your interiority. 
    <br/><br/>
    For so many of us, Kelela&#39;s music is a hand that keeps the faucet of that bravery and faith flowing. From there, it allows love in all forms to remain imaginable and inhabitable even amidst echo chambers of disappointment and the turmoil of endings and their associated transmogrifications. Her lyrics conduct us closer—Butch Morris style<sup><a href="#fn2" id="ref2">2</a></sup>—to the thrilling center of the risk inherent to all intimacy, and arm us with the improvisatory faculties we need to move together as the tectonic plates perpetually shift beneath and between us. In the crux of her willingness to acknowledge that all love &#40;like all improvisation&#41; requires us to practice faith <i> for real, </i> to put it all on the line with no assurances other than ourselves, she extends that valor, through the music, to those who listen. She slices away all the artifice just enough to give us permission to turn toward crevices of feeling we&#39;ve previously denied for fear of being swallowed. Whether she&#39;s expressing existential longing, renewal, anger, lamentation, delight, or rapture, her music wields blades that cut right into the inciting incidents our feelings emerge from, exposing their scintillating guts and in so doing, her music holds open a space in which to practice self-confrontation, not unlike what unfolds within the sanctum of a confession booth.
    <br/><br/>
    Certainly, the theological tonalities of Kelela&#39;s discography hold a pedagogical presence. She &#8220;<a href="https://open.spotify.com/episode/19jCr8yLdr9KJXSjXB93nT?si=6debd30d48604be0" target="_blank" className="styled"> takes love as seriously as scholarly work </a>&#8221; and her investment in studying the anatomy of her intimate life feeds directly into the fortitude of her eminent sound. Swathed in the sonic fog that emulates enraptured church organs throughout &#8220;<a href="https://www.youtube.com/watch?v=UEHpX1RQt7A" target="_blank" className="styled"> Holier </a>,&#8221; she reminds us that the holiest thing we can do is wear our hearts on our sleeves, refuse to hide the wound, and allow ourselves to be cradled in and by community: <i> &#8220;thought I was good but I&#39;m not / and though it troubles my heart / don&#39;t want to cover the scar / so I go where they hold me down.&#8221; </i> Her commitment to unwavering self-witnessing &#40;&#8220;that&#39;s what you&#39;re looking at… you are looking at me looking in the mirror,&#8221; she <a href="https://www.vulture.com/2023/02/kelela-raven.html" target="_blank" className="styled"> declares </a>&#41; beckons us to be earnest students of our own relational lives too, even when it hurts. In its &#8220;<a href="https://open.spotify.com/episode/19jCr8yLdr9KJXSjXB93nT?si=6debd30d48604be0" target="_blank" className="styled"> emotional integrity </a>,&#8221; her music is a teacher to me and, thus, takes a place beside the Black feminist writers and theorists that trace a vocabulary for the stakes of our relational dependencies. She stands tall next to the likes of Audre Lorde and bell hooks, both of whom advocate for fervent openness to feeling as pathways to freedom by way of their oft-cited &#8220;<a href="https://uk.sagepub.com/sites/default/files/upm-binaries/11881_Chapter_5.pdf" target="_blank" className="styled"> Uses of the Erotic </a>&#8221; &#40;1978&#41; and <a href="https://wtf.tw/ref/hooks.pdf" target="_blank" className="styled"> <i> All About Love </i> </a> &#40;1999&#41; as well as <a href="https://www.boaeditions.org/products/the-collected-poems-of-lucille-clifton?srsltid=AfmBOoo-CWMF6RWhAXlq8gU5ZtWybAQLMZTnfkJi0qvpm39S4llRQR2Q" target="_blank" className="styled"> Lucille Clifton </a>, <a href="https://rep.club/products/pursuit-revolutionary-love?srsltid=AfmBOooQLdFJwcASF6I_2R54YNy-VN_6F_5CFUfQuVQOyekAc_eNN1VW" target="_blank" className="styled"> Joy James </a>, <a href="https://deptof.love/Letter_2" target="_blank" className="styled"> Rhea Dillon </a> and so many others who preach the doctrine of vulnerability&#39;s pantheon of potentiality.
    <br/><br/>
    Kelela helps us conjure the tenacity to consider that we must remain available to all the ways love transforms us, even if some of it is brutal, even as some of it is ecstatic. When I put my headphones in and say yes to the seductively honest embrace of her offerings, I can let myself unravel, unspool, unfurl, melt, dissolve, and disintegrate. I can marshall the ability to refuse to abide by the impulse to protect myself from the threat of disappointment by repudiating the full range of my longings. In the company of her music, I may soak in the prodigious pool of my voraciousness and thus the fullness of my aliveness. 
    <br/><br/>
    Even as I position Kelela&#39;s music as a site of divinity and world-bending wisdom, it is crucial to name, also, the peril of the pedestal, the indignity of deification. As we watch those we once considered idols fall from grace, we are called to reconsider what we can and wish to expect from those we ostensibly look up to. That being said, Kelela has thus far defined herself as an artist who, along with the aforementioned emotional integrity within the sinews of her music and the lived life it teems out from, exists too along an unmistakable axis of artistic integrity. I understand such a quality as the development of one&#39;s own ethical positions and a persistent willingness to re-ascertain and shift them—both in word and in action—as new information is introduced into the equation and demands an alternative course of action, which is its own theistic and pedagogical tenet. 
    <br/><br/>
    She modeled this when she took a near <a href="https://www.nytimes.com/2023/02/02/arts/music/kelela-raven.html" target="_blank" className="styled"> six-year hiatus </a>,<sup><a href="#fn3" id="ref3">3</a></sup> which involved reevaluating her political alignment with her collaborators and drafting a multimedia syllabus of texts which she now shares with those she collaborates and/or shares close proximity with. Imagine it as a litmus test of their capacity to practice the behaviors needed to materialize a world that orients around and attends to Black women&#39;s safety, which is the same world her music imagines, emerges from, and wills into being. The syllabus is, like her sonic manifestos, an additional example of her concerted action of pulling closer to a reality that refuses to clip the wingspan of our wanting and, instead, insists upon the inhabitation of a feral life of feeling.
    <br/><br/>
    Another critical dimension of her artistic integrity lies in the precision and specificity with which she names her audience. Her open articulation of Black women and queer people as her addressees recalls the artist Simone Leigh&#39;s <a href="https://www.instagram.com/p/BxiJI58gl4t/?utm_source=ig_embed&utm_campaign=loading" target="_blank" className="styled"> articulation of Black women as her &#8220;primary audience&#8221; </a> and Toni Morrison&#39;s precise evocation that her &#8220;<a href="https://portsmouthinstitute.org/wp-content/uploads/2020/07/Morrison_Memory-Creation.pdf" target="_blank" className="styled">métier is Black.</a>&#8221; Kelela&#39;s integrity—both emotional and artistic—perhaps they&#39;re the same thing—makes her music a galvanizing place in which to land over, and over, and over again as it generously challenges me, as a listener, to model the same in my love and writing practices &#40;<i>perhaps they&#39;re the same thing </i>&#41;.  
    <br/><br/>
    {/* I return now to that floating beam at the Salt Shed, to how the contraption bathing Kelela in splendor reveals the infrastructure of its own illumination. As the synths swarm our senses and she invites us to look not only at the light, but where it spills out from, tonight&#39;s lesson becomes searingly clear: I must practice the bravery necessary to be a full participant in the thorny and thrilling entanglement that intimacy demands, to study my own center with a piercing degree of honesty, and to live in a more graciously complete relation with all four chambers of my own heart&#39;s horizons. If I hide the exquisitely fragile<sup><a href="#fn4" id="ref4">4</a></sup> infrastructure of my own illumination, I evade the risk inherent to what it means to embody integrity as a writer and as a lover alike. */}
    I return now to that floating beam at the Salt Shed, to how the contraption bathing Kelela in splendor revealed the infrastructure of its own illumination. As the synths swarmed our senses and she invited us to look not only at the light, but where it spills out from, the lesson became searingly clear: I must practice the bravery necessary to be a full participant in the thorny and thrilling entanglement that intimacy demands, study the contents of my own center with a piercing degree of veracity, and live in a more graciously complete relation with all four chambers of my own heart&#39;s horizons. 
    <br/><br/>
    The crescendo is yet to be realized. And so continues my edifying arch toward the unsteady yet assured sound of a thunder clap at the close of &#8220;<a href="https://www.youtube.com/watch?v=XQEGP3CaWEs" target="_blank" className="styled">Jupiter</a>&#8221; and the swelling precipice of Kelela&#39;s voice when she sings once more: &#8220;<i> I think I know me now. </i>&#8221; 
    </p> 
    <br/>
    <span className="footnotes camille">
    <p>
    <ol>
        <li id="fn1"> These parties, wherein Kelela invited local DJs to spin and reinterpret her new tracks took place in New York, D.C., and Los Angeles throughout Summer 2024.  <a href="#ref1">↩</a></li> <br/>
        <li id="fn2"> Butch Morris is credited for devising a practice of &#8220;conduction,&#8221; which allowed him to engineer a structure within which his band and those who shared the stage with him could improvise. The method involves a family of somatic semiotics, a series of hand gestures and expressions that guide the musicians in their collective freefall. <a href="#ref2">↩</a></li> <br/>
        <li id="fn3"> Such a move also models a refusal of extractive frameworks that equate one&#39;s visibility with their success and Kelela&#39;s trust that the enduring sustainability of her practice requires abiding by her own timescale, which I interpret as its own exuberant embodiment of emotional and artistic integrity alike. <a href="#ref3">↩</a></li> <br/>
        <li id="fn4"> I borrow this turn of phrase from the description of a Jo Malone fragrance called Peony & Blush Suede. <a href="#ref4">↩</a></li>
    </ol>
    </p>
    </span>
    <br/><br/><br/><br/><br/><br/>
    </div>
    </ArticleStyles>
  )
}
